/*
 * MIT License
 *
 * Copyright (c) 2026 stringdotjar
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.flixelgdx.gradle.shader;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Assembles the bgfx {@code shaderc} sources ({@code .sc} plus {@code varying.def.sc}) and the
 * ESSL sources for the web and Android backends from the plain GLSL a developer writes.
 *
 * <p>A game developer never has to learn bgfx's shader dialect. They write an ordinary GLSL
 * {@code void main()} that reads a small set of framework-provided names, and this class wraps that
 * body with the bgfx contract: the {@code $input}/{@code $output} declarations, the
 * {@code #include <bgfx_shader.sh>} preamble, the stage-0 sampler the batch binds, and a block of
 * {@code #define} aliases mapping the friendly names to bgfx's internal ones. This mirrors how the
 * HaxeFlixel compatibility layer in {@code FlixelShader} rewrites {@code #pragma header} shaders.
 *
 * <p>The same vertex body also runs on ESSL backends (web, Android) because {@link #esslVertex}
 * injects {@code #define} aliases that map the bgfx-side names ({@code a_texcoord0},
 * {@code a_color0}, {@code u_modelViewProj}, {@code mul}) to the matching ESSL declarations. A body
 * that compiles against the bgfx vertex contract will therefore compile unchanged on ESSL too,
 * provided it reads {@code a_position} as a {@code vec2} (which is what the framework's vertex
 * buffer actually contains).
 *
 * <p>The names available to a fragment shader are:
 * <ul>
 *   <li>{@code u_texture} - the sampler for the sprite or camera scene texture (bound at stage 0).</li>
 *   <li>{@code v_texCoords} - the interpolated texture coordinate ({@code vec2}).</li>
 *   <li>{@code v_color} - the interpolated vertex tint ({@code vec4}).</li>
 *   <li>{@code flixel_texture(uv)} - shorthand for {@code texture2D(u_texture, uv)}.</li>
 * </ul>
 * The shader writes its result to {@code gl_FragColor}. A developer must not redeclare these names;
 * the preamble already provides them, just like {@code #pragma header} does in HaxeFlixel.
 *
 * <p>The methods here are pure string transforms with no Gradle or file-system dependencies, so
 * they are unit tested directly.
 */
public final class ShaderSources {

  /**
   * The shared varying and attribute declarations both stages compile against.
   *
   * <p>This matches the vertex layout the desktop backend registers: position (2 floats),
   * texture coordinate (2 floats), and a packed color (4 normalized bytes).
   */
  public static final String VARYING_DEF = """
      vec2 v_texcoord0 : TEXCOORD0 = vec2(0.0, 0.0);
      vec4 v_color0    : COLOR0    = vec4(1.0, 1.0, 1.0, 1.0);

      vec2 a_position  : POSITION;
      vec2 a_texcoord0 : TEXCOORD0;
      vec4 a_color0    : COLOR0;
      """;

  /**
   * The built-in pass-through vertex shader used when a shader declares no custom vertex source.
   *
   * <p>Every quad corner is already transformed on the CPU by the batch, so the vertex stage only
   * applies the combined view-projection matrix and forwards the texture coordinate and tint. This
   * covers the overwhelming majority of sprite and camera post-processing effects, which only need
   * a custom fragment stage.
   */
  public static final String DEFAULT_VERTEX = """
      void main()
      {
        gl_Position = mul(u_modelViewProj, vec4(a_position.xy, 0.0, 1.0));
        v_texCoords = a_texcoord0;
        v_color = a_color0;
      }
      """;

  private static final String HEADER =
      "// Generated by the FlixelGDX shader plugin. Do not edit.\n";

  /**
   * Matches a single scalar or vector uniform declaration, such as {@code uniform float u_time;}.
   *
   * <p>Group 1 is the indentation, group 2 is the type, and group 3 is the name. Declarations with several names or an array
   * size are not matched and pass through unchanged.
   */
  private static final Pattern UNIFORM_DECLARATION = Pattern.compile(
      "^([ \\t]*)uniform\\s+(?:(?:lowp|mediump|highp)\\s+)?(float|int|vec2|vec3|vec4)\\s+(\\w+)\\s*;",
      Pattern.MULTILINE);

  /**
   * The ESSL pass-through vertex shader body, shared by both the no-custom-vertex path and
   * the custom-vertex path as a reference for what the preamble provides.
   *
   * <p>This vertex stage matches the web and Android backends' fixed vertex layout and attribute
   * names ({@code a_position}, {@code a_texCoord0}, {@code a_color}), forwarding the texture
   * coordinate and tint and applying the combined view-projection matrix.
   */
  private static final String ESSL_PASS_THROUGH_VERTEX = """
      attribute vec2 a_position;
      attribute vec2 a_texCoord0;
      attribute vec4 a_color;
      uniform mat4 u_projTrans;
      varying vec2 v_texCoords;
      varying vec4 v_color;
      void main() {
        v_texCoords = a_texCoord0;
        v_color = a_color;
        gl_Position = u_projTrans * vec4(a_position, 0.0, 1.0);
      }
      """;

  /**
   * The ESSL preamble prepended to a custom vertex body.
   *
   * <p>Declares the attributes, uniforms, and varyings, then defines aliases that let a vertex
   * body written against the bgfx naming convention compile unchanged:
   * <ul>
   *   <li>{@code a_texcoord0} maps to {@code a_texCoord0} (bgfx uses lowercase {@code c}).</li>
   *   <li>{@code a_color0} maps to {@code a_color} (bgfx uses a numeric suffix).</li>
   *   <li>{@code u_modelViewProj} maps to {@code u_projTrans} (different uniform name).</li>
   *   <li>{@code mul(a, b)} expands to {@code ((a) * (b))} (bgfx GLSL helper, absent in plain GLSL).</li>
   * </ul>
   *
   * <p>Note: {@code a_position} is declared as {@code vec2} here, matching the framework's vertex
   * buffer. A body that treats it as {@code vec4} (a form sometimes used in bgfx dialect) will not
   * compile on ESSL; write {@code vec4(a_position, 0.0, 1.0)} or {@code vec4(a_position.xy, 0.0, 1.0)}
   * instead, which works on both bgfx and ESSL.
   */
  private static final String ESSL_VERTEX_PREAMBLE = """
      attribute vec2 a_position;
      attribute vec2 a_texCoord0;
      attribute vec4 a_color;
      uniform mat4 u_projTrans;
      varying vec2 v_texCoords;
      varying vec4 v_color;
      #define a_texcoord0 a_texCoord0
      #define a_color0 a_color
      #define u_modelViewProj u_projTrans
      #define mul(a, b) ((a) * (b))
      """;

  /**
   * The fragment preamble prepended to the developer's source for the ESSL variant.
   *
   * <p>It provides the same friendly names the bgfx contract exposes ({@code u_texture},
   * {@code v_texCoords}, {@code v_color}, {@code flixel_texture}) but in browser-ready ESSL, so a
   * developer's fragment source compiles unchanged on the web and Android backends.
   */
  private static final String ESSL_FRAGMENT_PREAMBLE = """
      #ifdef GL_ES
      #ifdef GL_FRAGMENT_PRECISION_HIGH
      precision highp float;
      #else
      precision mediump float;
      #endif
      #endif
      uniform sampler2D u_texture;
      varying vec2 v_texCoords;
      varying vec4 v_color;
      vec4 flixel_texture(vec2 uv) { return texture2D(u_texture, uv); }
      """;

  /**
   * Words that are ordinary identifiers in GLSL but reserved in HLSL.
   *
   * <p>bgfx compiles the SPIR-V and Direct3D variants through an HLSL front end, so a GLSL variable
   * named {@code line} or {@code sample} fails there even though the desktop GLSL, Metal, Android,
   * and web variants accept it. Words that bgfx's own header uses (such as {@code register}) are
   * left out, because renaming them would break the header's macros.
   */
  private static final String[] HLSL_ONLY_KEYWORDS = {
      "compile", "dword", "globallycoherent", "groupshared", "line", "lineadj", "linear", "matrix",
      "nointerpolation", "packoffset", "pass", "point", "precise", "sample", "snorm", "string",
      "technique", "triangle", "triangleadj", "unorm", "vector"
  };

  /** Matches the start of a {@code vec2(}, {@code vec3(}, or {@code vec4(} constructor call. */
  private static final Pattern VECTOR_CONSTRUCTOR =
      Pattern.compile("(?<![\\w.])vec([234])\\s*\\(");

  /** Matches a plain numeric literal, such as {@code 0}, {@code 1.5}, or {@code -2.0}. */
  private static final Pattern NUMBER_LITERAL = Pattern.compile("-?\\d+(\\.\\d*)?([eE][-+]?\\d+)?");

  private ShaderSources() {}

  /**
   * Returns the ESSL vertex shader source for the web and Android backends.
   *
   * <p>When {@code vertexGlsl} is {@code null} or blank, the built-in pass-through is returned,
   * which covers the overwhelming majority of sprite and camera effects. When a custom vertex body
   * is supplied, it is wrapped with an ES 1.00 preamble that declares the attributes, uniforms, and
   * varyings, plus {@code #define} aliases so bodies written against the bgfx vertex naming
   * convention ({@code a_texcoord0}, {@code a_color0}, {@code u_modelViewProj}, {@code mul}) compile
   * unchanged on ESSL.
   *
   * <p>The one form that cannot be translated: treating {@code a_position} as {@code vec4}. The
   * framework's vertex buffer stores position as two floats ({@code vec2}), so the attribute is
   * declared as {@code vec2} here. Write {@code vec4(a_position, 0.0, 1.0)} to promote it safely,
   * which is compatible with both bgfx and ESSL.
   *
   * @param vertexGlsl The developer's vertex body, or {@code null} to use the built-in pass-through.
   * @return Complete ESSL vertex source ready to upload to the GPU.
   */
  @NotNull
  public static String esslVertex(@Nullable String vertexGlsl) {
    if (vertexGlsl == null || vertexGlsl.isBlank()) {
      return HEADER + ESSL_PASS_THROUGH_VERTEX;
    }
    return HEADER + "\n" + ESSL_VERTEX_PREAMBLE + "\n" + vertexGlsl.strip() + "\n";
  }

  /**
   * Wraps a developer's fragment GLSL in the ESSL fragment contract for the web and Android backends.
   *
   * @param fragmentGlsl The developer's fragment source, containing a {@code void main()}.
   * @return Complete ESSL fragment source ready to upload to the GPU.
   */
  @NotNull
  public static String esslFragment(@NotNull String fragmentGlsl) {
    return HEADER + "\n"
        + ESSL_FRAGMENT_PREAMBLE
        + "\n"
        + fragmentGlsl.strip()
        + "\n";
  }

  /**
   * Wraps a developer's fragment GLSL in the bgfx {@code .sc} fragment contract.
   *
   * @param fragmentGlsl The developer's fragment source, containing a {@code void main()}.
   * @return A complete bgfx fragment {@code .sc} source ready for {@code shaderc}.
   */
  @NotNull
  public static String fragment(@NotNull String fragmentGlsl) {
    return HEADER
        + "$input v_texcoord0, v_color0\n\n"
        + "#include <bgfx_shader.sh>\n\n"
        + "SAMPLER2D(s_texture, 0);\n\n"
        + "#define u_texture s_texture\n"
        + "#define v_texCoords v_texcoord0\n"
        + "#define v_color v_color0\n"
        + "#define flixel_texture(_uv) texture2D(s_texture, _uv)\n"
        + renameHlslKeywords(fragmentGlsl)
        + "\n"
        + bgfxBody(fragmentGlsl)
        + "\n";
  }

  /**
   * Wraps a vertex stage in the bgfx {@code .sc} vertex contract, using the built-in pass-through
   * source when no custom one is supplied.
   *
   * <p>A custom vertex shader may read {@code a_position} ({@code vec2}), {@code a_texcoord0}
   * ({@code vec2}), and {@code a_color0} ({@code vec4}), transform with {@code u_modelViewProj},
   * and must write {@code v_texCoords} and {@code v_color} for the fragment stage.
   *
   * @param vertexGlsl The developer's vertex source, or {@code null} to use {@link #DEFAULT_VERTEX}.
   * @return A complete bgfx vertex {@code .sc} source ready for {@code shaderc}.
   */
  @NotNull
  public static String vertex(@Nullable String vertexGlsl) {
    String body = (vertexGlsl == null || vertexGlsl.isBlank()) ? DEFAULT_VERTEX : vertexGlsl;
    return HEADER
        + "$input a_position, a_texcoord0, a_color0\n"
        + "$output v_texcoord0, v_color0\n\n"
        + "#include <bgfx_shader.sh>\n\n"
        + "#define v_texCoords v_texcoord0\n"
        + "#define v_color v_color0\n"
        + renameHlslKeywords(body)
        + "\n"
        + bgfxBody(body)
        + "\n";
  }

  /**
   * Rewrites scalar and vector uniforms into the {@code vec4} form bgfx requires.
   *
   * <p>bgfx only understands {@code vec4}, {@code mat3}, {@code mat4}, and sampler uniforms. A plain
   * {@code uniform float u_time;} is silently dropped from the desktop GLSL variant and fails to
   * compile to SPIR-V, so every {@code float}, {@code int}, {@code vec2}, {@code vec3}, and
   * {@code vec4} uniform is declared as a {@code vec4} under the same name, followed by a macro
   * that reads back the original type:
   *
   * <pre>{@code
   * uniform float u_time;   // becomes: uniform vec4 u_time;
   *                         //          #define u_time u_time.x
   * }</pre>
   *
   * <p>A macro that names itself is only expanded once, so every later use of {@code u_time} reads
   * {@code u_time.x} while the declaration above it keeps the real name. The desktop backend
   * therefore finds the uniform under the exact name game code passes to {@code setUniform(...)}.
   * Precision qualifiers are dropped because bgfx declares its own.
   *
   * @param glsl The developer's shader source.
   * @return The source with each matching uniform promoted to {@code vec4}.
   */
  @NotNull
  static String promoteUniforms(@NotNull String glsl) {
    Matcher matcher = UNIFORM_DECLARATION.matcher(glsl);
    StringBuilder out = new StringBuilder(glsl.length() + 64);
    while (matcher.find()) {
      String indent = matcher.group(1);
      String type = matcher.group(2);
      String name = matcher.group(3);
      String read = switch (type) {
        case "float" -> name + ".x";
        case "int" -> "int(" + name + ".x)";
        case "vec2" -> name + ".xy";
        case "vec3" -> name + ".xyz";
        default -> null;
      };
      String replacement = indent + "uniform vec4 " + name + ";";
      if (read != null) {
        replacement += "\n" + indent + "#define " + name + " " + read;
      }
      matcher.appendReplacement(out, Matcher.quoteReplacement(replacement));
    }
    matcher.appendTail(out);
    return out.toString();
  }

  /**
   * Returns macros that rename every HLSL-only reserved word the source uses as an identifier.
   *
   * <p>For example, a source that declares {@code float line;} gets {@code #define line flx_line}, so
   * the HLSL front end behind the SPIR-V and Direct3D variants sees {@code flx_line} instead of the
   * reserved {@code line}. Other backends compile the renamed code just the same.
   *
   * @param glsl The developer's shader source.
   * @return One {@code #define} line per reserved word found, or an empty string.
   */
  @NotNull
  static String renameHlslKeywords(@NotNull String glsl) {
    StringBuilder out = new StringBuilder();
    for (String word : HLSL_ONLY_KEYWORDS) {
      if (Pattern.compile("\\b" + word + "\\b").matcher(glsl).find()) {
        out.append("#define ").append(word).append(" flx_").append(word).append('\n');
      }
    }
    return out.toString();
  }

  /**
   * Prepares a developer's shader body for {@code shaderc}: promotes uniforms and replaces
   * single-argument vector constructors, adding the helper functions the replacements call.
   *
   * @param glsl The developer's shader source.
   * @return The rewritten body, preceded by any helper functions it needs.
   */
  @NotNull
  private static String bgfxBody(@NotNull String glsl) {
    String body = expandVectorConstructors(promoteUniforms(glsl.strip()));
    StringBuilder helpers = new StringBuilder();
    if (body.contains("flx_vec2(")) {
      helpers.append("vec2 flx_vec2(float x) { return vec2(x, x); }\n")
          .append("vec2 flx_vec2(vec2 v) { return v; }\n")
          .append("vec2 flx_vec2(vec3 v) { return v.xy; }\n")
          .append("vec2 flx_vec2(vec4 v) { return v.xy; }\n");
    }
    if (body.contains("flx_vec3(")) {
      helpers.append("vec3 flx_vec3(float x) { return vec3(x, x, x); }\n")
          .append("vec3 flx_vec3(vec3 v) { return v; }\n")
          .append("vec3 flx_vec3(vec4 v) { return v.xyz; }\n");
    }
    if (body.contains("flx_vec4(")) {
      helpers.append("vec4 flx_vec4(float x) { return vec4(x, x, x, x); }\n")
          .append("vec4 flx_vec4(vec4 v) { return v; }\n");
    }
    return helpers.length() == 0 ? body : helpers + "\n" + body;
  }

  /**
   * Rewrites every single-argument vector constructor into a form HLSL accepts.
   *
   * <p>GLSL lets {@code vec3(x)} fill every component with one value, or narrow a larger vector.
   * HLSL, which bgfx uses for the SPIR-V and Direct3D variants, rejects both with "incorrect number
   * of arguments". The argument's type cannot be known from the text alone, so the call becomes a
   * call to an overloaded helper ({@code flx_vec3(x)}) that the compiler resolves by type:
   *
   * <pre>{@code
   * vec3(gray)        // becomes: flx_vec3(gray)
   * vec2(0.0)         // becomes: vec2(0.0, 0.0), since a number is always a scalar
   * }</pre>
   *
   * <p>A {@code const} declaration cannot call a function, so there the argument is repeated for
   * each component instead, which is correct for the scalar values constants are built from.
   *
   * @param glsl The shader source.
   * @return The source with every single-argument vector constructor rewritten.
   */
  @NotNull
  static String expandVectorConstructors(@NotNull String glsl) {
    StringBuilder out = new StringBuilder(glsl.length() + 64);
    Matcher matcher = VECTOR_CONSTRUCTOR.matcher(glsl);
    int copied = 0;
    int searchFrom = 0;
    while (matcher.find(searchFrom)) {
      int open = matcher.end() - 1;
      int close = findClosingParen(glsl, open);
      if (close < 0) {
        break;
      }
      String argument = glsl.substring(open + 1, close);
      int size = matcher.group(1).charAt(0) - '0';
      out.append(glsl, copied, matcher.start());
      if (hasTopLevelComma(argument) || argument.isBlank()) {
        out.append(glsl, matcher.start(), open + 1).append(expandVectorConstructors(argument)).append(')');
      } else {
        String inner = expandVectorConstructors(argument).strip();
        if (NUMBER_LITERAL.matcher(inner).matches() || isInConstDeclaration(glsl, matcher.start())) {
          out.append("vec").append(size).append('(');
          for (int i = 0; i < size; i++) {
            out.append(i == 0 ? "" : ", ").append(inner);
          }
          out.append(')');
        } else {
          out.append("flx_vec").append(size).append('(').append(inner).append(')');
        }
      }
      copied = close + 1;
      searchFrom = close + 1;
    }
    out.append(glsl, copied, glsl.length());
    return out.toString();
  }

  /**
   * Returns the index of the parenthesis that closes the one at {@code open}, or {@code -1}.
   *
   * @param text The source text.
   * @param open The index of an opening parenthesis.
   * @return The index of the matching closing parenthesis, or {@code -1} when there is none.
   */
  private static int findClosingParen(@NotNull String text, int open) {
    int depth = 0;
    for (int i = open; i < text.length(); i++) {
      char c = text.charAt(i);
      if (c == '(') {
        depth++;
      } else if (c == ')' && --depth == 0) {
        return i;
      }
    }
    return -1;
  }

  /**
   * Returns whether an argument list has a comma outside any nested parentheses or brackets.
   *
   * @param argument The text between a call's parentheses.
   * @return {@code true} when the call has more than one argument.
   */
  private static boolean hasTopLevelComma(@NotNull String argument) {
    int depth = 0;
    for (int i = 0; i < argument.length(); i++) {
      char c = argument.charAt(i);
      if (c == '(' || c == '[') {
        depth++;
      } else if (c == ')' || c == ']') {
        depth--;
      } else if (c == ',' && depth == 0) {
        return true;
      }
    }
    return false;
  }

  /**
   * Returns whether the statement containing {@code index} starts with {@code const}.
   *
   * @param text The source text.
   * @param index A position inside the statement.
   * @return {@code true} when the statement is a {@code const} declaration.
   */
  private static boolean isInConstDeclaration(@NotNull String text, int index) {
    int start = index;
    while (start > 0) {
      char c = text.charAt(start - 1);
      if (c == ';' || c == '{' || c == '}') {
        break;
      }
      start--;
    }
    return text.substring(start, index).strip().startsWith("const ");
  }

  /**
   * Returns the shared {@code varying.def.sc} contents both stages are compiled against.
   *
   * @return The varying definition source.
   */
  @NotNull
  public static String varyingDef() {
    return HEADER + VARYING_DEF;
  }
}
