/*
 * MIT License
 *
 * Copyright (c) 2026 stringdotjar
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.flixelgdx.gradle.shader;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * Assembles the bgfx {@code shaderc} sources ({@code .sc} plus {@code varying.def.sc}) from the
 * plain GLSL a developer writes.
 *
 * <p>A game developer never has to learn bgfx's shader dialect. They write an ordinary GLSL
 * {@code void main()} that reads a small set of framework-provided names, and this class wraps that
 * body with the bgfx contract: the {@code $input}/{@code $output} declarations, the
 * {@code #include <bgfx_shader.sh>} preamble, the stage-0 sampler the batch binds, and a block of
 * {@code #define} aliases mapping the friendly names to bgfx's internal ones. This mirrors how the
 * HaxeFlixel compatibility layer in {@code FlixelShader} rewrites {@code #pragma header} shaders.
 *
 * <p>The names available to a fragment shader are:
 * <ul>
 *   <li>{@code u_texture} - the sampler for the sprite or camera scene texture (bound at stage 0).</li>
 *   <li>{@code v_texCoords} - the interpolated texture coordinate ({@code vec2}).</li>
 *   <li>{@code v_color} - the interpolated vertex tint ({@code vec4}).</li>
 *   <li>{@code flixel_texture(uv)} - shorthand for {@code texture2D(u_texture, uv)}.</li>
 * </ul>
 * The shader writes its result to {@code gl_FragColor}. A developer must not redeclare these names;
 * the preamble already provides them, just like {@code #pragma header} does in HaxeFlixel.
 *
 * <p>The methods here are pure string transforms with no Gradle or file-system dependencies, so
 * they are unit tested directly.
 */
public final class ShaderSources {

  /**
   * The shared varying and attribute declarations both stages compile against.
   *
   * <p>This matches the vertex layout the desktop backend registers: position (2 floats),
   * texture coordinate (2 floats), and a packed color (4 normalized bytes).
   */
  public static final String VARYING_DEF = """
      vec2 v_texcoord0 : TEXCOORD0 = vec2(0.0, 0.0);
      vec4 v_color0    : COLOR0    = vec4(1.0, 1.0, 1.0, 1.0);

      vec2 a_position  : POSITION;
      vec2 a_texcoord0 : TEXCOORD0;
      vec4 a_color0    : COLOR0;
      """;

  /**
   * The built-in pass-through vertex shader used when a shader declares no custom vertex source.
   *
   * <p>Every quad corner is already transformed on the CPU by the batch, so the vertex stage only
   * applies the combined view-projection matrix and forwards the texture coordinate and tint. This
   * covers the overwhelming majority of sprite and camera post-processing effects, which only need
   * a custom fragment stage.
   */
  public static final String DEFAULT_VERTEX = """
      void main()
      {
        gl_Position = mul(u_modelViewProj, vec4(a_position.xy, 0.0, 1.0));
        v_texCoords = a_texcoord0;
        v_color = a_color0;
      }
      """;

  private static final String HEADER =
      "// Generated by the FlixelGDX shader plugin. Do not edit.\n";

  /**
   * The pass-through vertex shader for the web (ESSL) variant.
   *
   * <p>The web backend renders through raw WebGL rather than bgfx, so its shaders are plain ESSL
   * text compiled in the browser. This vertex stage matches the web backend's fixed vertex layout
   * and attribute names ({@code a_position}, {@code a_texCoord0}, {@code a_color}), forwarding the
   * texture coordinate and tint and applying the combined view-projection matrix.
   */
  private static final String WEB_VERTEX = """
      attribute vec2 a_position;
      attribute vec2 a_texCoord0;
      attribute vec4 a_color;
      uniform mat4 u_projTrans;
      varying vec2 v_texCoords;
      varying vec4 v_color;
      void main() {
        v_texCoords = a_texCoord0;
        v_color = a_color;
        gl_Position = u_projTrans * vec4(a_position, 0.0, 1.0);
      }
      """;

  /**
   * The fragment preamble prepended to the developer's source for the web (ESSL) variant.
   *
   * <p>It provides the same friendly names the bgfx contract exposes ({@code u_texture},
   * {@code v_texCoords}, {@code v_color}, {@code flixel_texture}) but in browser-ready ESSL, so a
   * developer's fragment source compiles unchanged on the web.
   */
  private static final String WEB_FRAGMENT_PREAMBLE = """
      #ifdef GL_ES
      precision mediump float;
      #endif
      uniform sampler2D u_texture;
      uniform vec2 u_textureSize;
      varying vec2 v_texCoords;
      varying vec4 v_color;
      vec4 flixel_texture(vec2 uv) { return texture2D(u_texture, uv); }
      """;

  private ShaderSources() {}

  /**
   * Returns the pass-through vertex shader for the web (ESSL) variant.
   *
   * <p>Custom vertex stages are authored in the bgfx dialect and are not translated for the web, so
   * the web variant always uses this built-in pass-through, which covers the fragment-only shaders
   * that make up the overwhelming majority of effects.
   *
   * @return Complete ESSL vertex source ready for the browser.
   */
  @NotNull
  public static String webVertex() {
    return "// Generated by the FlixelGDX shader plugin. Do not edit.\n" + WEB_VERTEX;
  }

  /**
   * Wraps a developer's fragment GLSL in the web (ESSL) fragment contract.
   *
   * @param fragmentGlsl The developer's fragment source, containing a {@code void main()}.
   * @return Complete ESSL fragment source ready for the browser.
   */
  @NotNull
  public static String webFragment(@NotNull String fragmentGlsl) {
    return "// Generated by the FlixelGDX shader plugin. Do not edit.\n\n"
        + WEB_FRAGMENT_PREAMBLE
        + "\n"
        + fragmentGlsl.strip()
        + "\n";
  }

  /**
   * Wraps a developer's fragment GLSL in the bgfx {@code .sc} fragment contract.
   *
   * @param fragmentGlsl The developer's fragment source, containing a {@code void main()}.
   * @return A complete bgfx fragment {@code .sc} source ready for {@code shaderc}.
   */
  @NotNull
  public static String fragment(@NotNull String fragmentGlsl) {
    return HEADER
        + "$input v_texcoord0, v_color0\n\n"
        + "#include <bgfx_shader.sh>\n\n"
        + "SAMPLER2D(s_texture, 0);\n\n"
        + "#define u_texture s_texture\n"
        + "#define v_texCoords v_texcoord0\n"
        + "#define v_color v_color0\n"
        + "#define flixel_texture(_uv) texture2D(s_texture, _uv)\n\n"
        + fragmentGlsl.strip()
        + "\n";
  }

  /**
   * Wraps a vertex stage in the bgfx {@code .sc} vertex contract, using the built-in pass-through
   * source when no custom one is supplied.
   *
   * <p>A custom vertex shader may read {@code a_position} ({@code vec2}), {@code a_texcoord0}
   * ({@code vec2}), and {@code a_color0} ({@code vec4}), transform with {@code u_modelViewProj},
   * and must write {@code v_texCoords} and {@code v_color} for the fragment stage.
   *
   * @param vertexGlsl The developer's vertex source, or {@code null} to use {@link #DEFAULT_VERTEX}.
   * @return A complete bgfx vertex {@code .sc} source ready for {@code shaderc}.
   */
  @NotNull
  public static String vertex(@Nullable String vertexGlsl) {
    String body = (vertexGlsl == null || vertexGlsl.isBlank()) ? DEFAULT_VERTEX : vertexGlsl;
    return HEADER
        + "$input a_position, a_texcoord0, a_color0\n"
        + "$output v_texcoord0, v_color0\n\n"
        + "#include <bgfx_shader.sh>\n\n"
        + "#define v_texCoords v_texcoord0\n"
        + "#define v_color v_color0\n\n"
        + body.strip()
        + "\n";
  }

  /**
   * Returns the shared {@code varying.def.sc} contents both stages are compiled against.
   *
   * @return The varying definition source.
   */
  @NotNull
  public static String varyingDef() {
    return HEADER + VARYING_DEF;
  }
}
