/*
 * MIT License
 *
 * Copyright (c) 2026 stringdotjar
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
// AUTO-GENERATED by the framework via a Python script, located inside of the scripts/
// folder in the repository root. Do NOT edit this file directly. If you wish to change
// a framework collection API, modify the script so it affects all files in the collection package.
// For more information, visit the framework's repository on GitHub: https://github.com/flixelgdx/flixelgdx
package org.flixelgdx.collections;

import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.Map;
import java.util.Random;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class FlixelObject{{ValueTypeName}}MapTest {

  @Test
  void basicsAndDefaults() {
    FlixelObject{{ValueTypeName}}Map<String> map = new FlixelObject{{ValueTypeName}}Map<>();
    assertEquals({{valueZero}}, map.get("x", {{valueZero}}){{valueDelta}});
    map.put("x", ({{valueType}}) 10);
    assertEquals(({{valueType}}) 10, map.get("x", {{valueZero}}){{valueDelta}});
    assertEquals(({{valueType}}) 11, map.increment("x", ({{valueType}}) 1){{valueDelta}});
    assertTrue(map.containsKey("x"));
    assertThrows(IllegalArgumentException.class, () -> map.put(null, ({{valueType}}) 1));
    assertEquals(({{valueType}}) 11, map.remove("x", ({{valueType}}) -1){{valueDelta}});
    assertFalse(map.containsKey("x"));
  }

  @Test
  void entriesIterateEveryEntry() {
    FlixelObject{{ValueTypeName}}Map<String> map = new FlixelObject{{ValueTypeName}}Map<>();
    map.put("a", ({{valueType}}) 1);
    map.put("b", ({{valueType}}) 2);
    map.put("c", ({{valueType}}) 3);

    int count = 0;
    {{valueType}} sum = {{valueZero}};
    for (FlixelObject{{ValueTypeName}}Map.Entry<String> e : map.entries()) {
      sum += e.value;
      count++;
    }
    assertEquals(3, count);
    assertEquals(({{valueType}}) 6, sum{{valueDelta}});
  }

  @Test
  void behavesLikeHashMapUnderRandomOps() {
    FlixelObject{{ValueTypeName}}Map<Integer> ours = new FlixelObject{{ValueTypeName}}Map<>(4);
    Map<Integer, {{ValueBoxed}}> ref = new HashMap<>();
    Random random = new Random(33);
    for (int i = 0; i < 20000; i++) {
      Integer key = random.nextInt(400);
      int op = random.nextInt(3);
      if (op == 0) {
        {{valueType}} value = ({{valueType}}) random.nextInt(1000);
        ref.put(key, value);
        ours.put(key, value);
      } else if (op == 1) {
        {{ValueBoxed}} removed = ref.remove(key);
        assertEquals(removed == null ? ({{valueType}}) -999 : removed, ours.remove(key, ({{valueType}}) -999){{valueDelta}});
      } else {
        {{ValueBoxed}} v = ref.get(key);
        assertEquals(v == null ? ({{valueType}}) -999 : v, ours.get(key, ({{valueType}}) -999){{valueDelta}});
      }
      assertEquals(ref.size(), ours.getSize());
    }
  }
}
