/*
 * MIT License
 *
 * Copyright (c) 2026 stringdotjar
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
// AUTO-GENERATED by the framework via a Python script, located inside of the scripts/
// folder in the repository root. Do NOT edit this file directly. If you wish to change
// a framework collection API, modify the script so it affects all files in the collection package.
// For more information, visit the framework's repository on GitHub: https://github.com/flixelgdx/flixelgdx
package org.flixelgdx.collections;

import org.jetbrains.annotations.NotNull;

import java.util.Arrays;
import java.util.Iterator;
import java.util.NoSuchElementException;

/**
 * An unordered map from object keys to primitive {@code {{valueType}}} values.
 *
 * <p>The values are stored without boxing, which suits counters and lookup
 * tables keyed by object. Because the values are primitive, reads take a
 * fallback to return when a key is absent (there is no {@code null}).
 *
 * <p>Keys must not be {@code null}. Iteration order is undefined.
 *
 * <p>This class is not thread safe.
 *
 * @param <K> The key type.
 */
public class FlixelObject{{ValueTypeName}}Map<K> {

  private static final int DEFAULT_CAPACITY = 16;
  private static final float LOAD_FACTOR = 0.75f;
  private static final int HASH_MULTIPLIER = 0x9E3779B1;

  private K[] keyTable;
  private {{valueType}}[] valueTable;
  private int size;
  private int mask;
  private int threshold;
  private int shift;

  private Entries<K> entries;

  /**
   * Creates an empty map with the default initial capacity.
   */
  public FlixelObject{{ValueTypeName}}Map() {
    this(DEFAULT_CAPACITY);
  }

  /**
   * Creates an empty map sized to hold at least the given number of entries
   * before it needs to grow.
   *
   * @param initialCapacity The expected entry count.
   */
  @SuppressWarnings("unchecked")
  public FlixelObject{{ValueTypeName}}Map(int initialCapacity) {
    int cap = tableSizeFor(Math.max(1, initialCapacity));
    keyTable = (K[]) new Object[cap];
    valueTable = new {{valueType}}[cap];
    mask = cap - 1;
    threshold = (int) (cap * LOAD_FACTOR);
    shift = Integer.numberOfLeadingZeros(mask);
  }

  /**
   * Associates a value with a key, replacing any previous value.
   *
   * @param key The key; must not be {@code null}.
   * @param value The value to store.
   * @throws IllegalArgumentException If {@code key} is {@code null}.
   */
  public void put(@NotNull K key, {{valueType}} value) {
    if (key == null) {
      throw new IllegalArgumentException("key cannot be null");
    }
    int i = locate(key);
    if (keyTable[i] != null) {
      valueTable[i] = value;
      return;
    }
    keyTable[i] = key;
    valueTable[i] = value;
    if (++size >= threshold) {
      resize(keyTable.length << 1);
    }
  }

  /**
   * Returns the value stored under a key, or a fallback if the key is absent.
   *
   * @param key The key to look up.
   * @param defaultValue The value to return when the key is not present.
   * @return The associated value, or the fallback if the key is absent.
   */
  public {{valueType}} get(@NotNull K key, {{valueType}} defaultValue) {
    int i = locate(key);
    return keyTable[i] == null ? defaultValue : valueTable[i];
  }

  /**
   * Adds an amount to the value stored under a key, treating an absent key as a
   * starting value of zero.
   *
   * @param key The key; must not be {@code null}.
   * @param amount The amount to add.
   * @return The new value stored under the key.
   */
  public {{valueType}} increment(@NotNull K key, {{valueType}} amount) {
    {{valueType}} updated = ({{valueType}}) (get(key, {{valueZero}}) + amount);
    put(key, updated);
    return updated;
  }

  /**
   * Reports whether a key is present.
   *
   * @param key The key to check.
   * @return {@code true} if the key has an entry.
   */
  public boolean containsKey(@NotNull K key) {
    return keyTable[locate(key)] != null;
  }

  /**
   * Removes the entry for a key, if present.
   *
   * @param key The key to remove.
   * @param defaultValue The value to return when the key is absent.
   * @return The value that was removed, or the fallback if the key was absent.
   */
  public {{valueType}} remove(@NotNull K key, {{valueType}} defaultValue) {
    int i = locate(key);
    if (keyTable[i] == null) {
      return defaultValue;
    }
    {{valueType}} oldValue = valueTable[i];
    int next = (i + 1) & mask;
    while (keyTable[next] != null) {
      int ideal = place(keyTable[next]);
      if (((next - ideal) & mask) >= ((next - i) & mask)) {
        keyTable[i] = keyTable[next];
        valueTable[i] = valueTable[next];
        i = next;
      }
      next = (next + 1) & mask;
    }
    keyTable[i] = null;
    size--;
    return oldValue;
  }

  /**
   * Removes every entry, leaving the map empty.
   */
  public void clear() {
    Arrays.fill(keyTable, null);
    size = 0;
  }

  /**
   * Returns the number of entries.
   *
   * @return The entry count.
   */
  public int getSize() {
    return size;
  }

  /**
   * Reports whether the map has no entries.
   *
   * @return {@code true} if empty.
   */
  public boolean isEmpty() {
    return size == 0;
  }

  /**
   * Returns a reusable iterable over the map's entries.
   *
   * @return An iterable whose {@link Entry} is reused each step.
   */
  public @NotNull Entries<K> entries() {
    if (entries == null) {
      entries = new Entries<>(this);
    }
    entries.reset();
    return entries;
  }

  private int place(K key) {
    return (key.hashCode() * HASH_MULTIPLIER) >>> shift;
  }

  private int locate(K key) {
    int i = place(key);
    while (true) {
      K existing = keyTable[i];
      if (existing == null || existing.equals(key)) {
        return i;
      }
      i = (i + 1) & mask;
    }
  }

  @SuppressWarnings("unchecked")
  private void resize(int newSize) {
    K[] oldKeys = keyTable;
    {{valueType}}[] oldValues = valueTable;
    keyTable = (K[]) new Object[newSize];
    valueTable = new {{valueType}}[newSize];
    mask = newSize - 1;
    threshold = (int) (newSize * LOAD_FACTOR);
    shift = Integer.numberOfLeadingZeros(mask);
    for (int i = 0; i < oldKeys.length; i++) {
      K key = oldKeys[i];
      if (key != null) {
        int j = locate(key);
        keyTable[j] = key;
        valueTable[j] = oldValues[i];
      }
    }
  }

  private static int tableSizeFor(int capacity) {
    int needed = (int) (capacity / LOAD_FACTOR) + 1;
    int size = 2;
    while (size < needed) {
      size <<= 1;
    }
    return size;
  }

  /**
   * A single key-value pair yielded by {@link #entries()}.
   *
   * <p>The same instance is reused across iteration steps.
   *
   * @param <K> The key type.
   */
  public static final class Entry<K> {

    /** The entry's key. */
    public K key;

    /** The entry's value. */
    public {{valueType}} value;
  }

  /**
   * A reusable iterable over a map's entries.
   *
   * @param <K> The key type.
   */
  public static final class Entries<K> implements Iterable<Entry<K>>, Iterator<Entry<K>> {

    private final FlixelObject{{ValueTypeName}}Map<K> map;
    private final Entry<K> entry = new Entry<>();
    private int index;
    private boolean hasNext;

    Entries(FlixelObject{{ValueTypeName}}Map<K> map) {
      this.map = map;
    }

    void reset() {
      index = -1;
      advance();
    }

    void advance() {
      hasNext = false;
      K[] keyTable = map.keyTable;
      for (index++; index < keyTable.length; index++) {
        if (keyTable[index] != null) {
          hasNext = true;
          break;
        }
      }
    }

    @Override
    public @NotNull Iterator<Entry<K>> iterator() {
      return this;
    }

    @Override
    public boolean hasNext() {
      return hasNext;
    }

    @Override
    public Entry<K> next() {
      if (!hasNext) {
        throw new NoSuchElementException();
      }
      entry.key = map.keyTable[index];
      entry.value = map.valueTable[index];
      advance();
      return entry;
    }
  }
}
