/*
 * MIT License
 *
 * Copyright (c) 2026 stringdotjar
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.flixelgdx.gradle.packagr;

import java.util.List;

/**
 * Builds the {@code packagr.cfg} file the native launcher reads at startup.
 *
 * <p>The launcher is a small compiled program with no knowledge of any particular game; everything
 * it needs to start the JVM lives in this plain-text file sitting next to it. The format is a line
 * per setting, {@code key=value}, chosen so the launcher can parse it with a few lines of C:
 *
 * <pre>{@code
 * main=com.mygame.DesktopLauncher
 * jre=jre
 * libs=lib
 * vmarg=-Xmx1G
 * vmarg=-XX:+UseZGC
 * }</pre>
 *
 * <p>The {@code main} key is the class to launch, {@code jre} and {@code libs} are the bundled
 * runtime and classpath directories (relative to the launcher), and each {@code vmarg} line is one
 * argument handed to the JVM. A blank line or a line starting with {@code #} is ignored.
 */
public final class LaunchConfig {

  private static final String JRE_DIR = "jre";
  private static final String LIBS_DIR = "lib";

  private LaunchConfig() {}

  /**
   * Renders the launch configuration file contents.
   *
   * @param mainClass The fully qualified main class to launch.
   * @param jvmArgs The extra arguments to pass to the JVM, in order.
   * @return The full text of the {@code packagr.cfg} file, ending with a newline.
   */
  public static String render(String mainClass, List<String> jvmArgs) {
    StringBuilder sb = new StringBuilder();
    sb.append("# Generated by the FlixelGDX packagr plugin. Do not edit by hand.\n");
    sb.append("main=").append(mainClass).append('\n');
    sb.append("jre=").append(JRE_DIR).append('\n');
    sb.append("libs=").append(LIBS_DIR).append('\n');
    for (String arg : jvmArgs) {
      sb.append("vmarg=").append(arg).append('\n');
    }
    return sb.toString();
  }
}
