[versions]
agp = "8.7.3"
asm = "9.7.1"
desugarJdkLibs = "2.1.5"
graalvm = "24.2.0"
jansi = "2.4.2"
jetbrainsAnnotations = "26.1.0"
junit = "5.10.0"
kotlin = "2.2.20"
lwjgl = "3.4.2"
multidex = "2.0.1"
spotless = "8.6.0"
teavm = "0.13.0"
vanniktech = "0.33.0"

[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-tree = { module = "org.ow2.asm:asm-tree", version.ref = "asm" }
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarJdkLibs" }
graalvm-nativeimage = { module = "org.graalvm.sdk:nativeimage", version.ref = "graalvm" }
jansi = { module = "org.fusesource.jansi:jansi", version.ref = "jansi" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrainsAnnotations" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
lwjgl = { module = "org.lwjgl:lwjgl" }
lwjgl-bgfx = { module = "org.lwjgl:lwjgl-bgfx" }
lwjgl-sdl = { module = "org.lwjgl:lwjgl-sdl" }
lwjgl-stb = { module = "org.lwjgl:lwjgl-stb" }
lwjgl-zstd = { module = "org.lwjgl:lwjgl-zstd" }
multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
teavm-gradle-plugin = { module = "org.teavm:teavm-gradle-plugin", version.ref = "teavm" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
teavm = { id = "org.teavm", version.ref = "teavm" }
vanniktech = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech" }
