/*
 * MIT License
 *
 * Copyright (c) 2026 stringdotjar
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
// AUTO-GENERATED by the framework via a Python script, located inside of the scripts/
// folder in the repository root. Do NOT edit this file directly. If you wish to change
// a framework collection API, modify the script so it affects all files in the collection package.
// For more information, visit the framework's repository on GitHub: https://github.com/flixelgdx/flixelgdx
package org.flixelgdx.collections;

import org.junit.jupiter.api.Test;

import java.util.HashSet;
import java.util.Random;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class FlixelLongSetTest {

  @Test
  void addContainsRemove() {
    FlixelLongSet set = new FlixelLongSet();
    assertTrue(set.add((long) 5));
    assertFalse(set.add((long) 5));
    assertTrue(set.contains((long) 5));
    assertTrue(set.remove((long) 5));
    assertFalse(set.contains((long) 5));
    assertTrue(set.isEmpty());
  }

  @Test
  void zeroIsHandledSpecially() {
    FlixelLongSet set = new FlixelLongSet();
    assertFalse(set.contains(0L));
    assertTrue(set.add(0L));
    assertFalse(set.add(0L));
    assertTrue(set.contains(0L));
    assertEquals(1, set.getSize());
    assertTrue(set.remove(0L));
    assertFalse(set.contains(0L));
  }

  @Test
  void iteratorVisitsEveryValue() {
    FlixelLongSet set = new FlixelLongSet();
    set.add(0L);
    set.add((long) 1);
    set.add((long) 2);

    long sum = 0;
    int count = 0;
    for (FlixelLongSet.LongSetIterator it = set.iterator(); it.hasNext;) {
      sum += it.next();
      count++;
    }
    assertEquals(3, count);
    assertEquals(3, sum);
  }

  @Test
  void behavesLikeHashSetUnderRandomOps() {
    FlixelLongSet ours = new FlixelLongSet(4);
    Set<Long> ref = new HashSet<>();
    Random random = new Random(13);

    for (int i = 0; i < 20000; i++) {
      long value = (long) (random.nextInt(300) - 40);
      int op = random.nextInt(3);
      if (op == 0) {
        assertEquals(ref.add(value), ours.add(value));
      } else if (op == 1) {
        assertEquals(ref.remove(value), ours.remove(value));
      } else {
        assertEquals(ref.contains(value), ours.contains(value));
      }
      assertEquals(ref.size(), ours.getSize());
    }
  }
}
