/*
 * MIT License
 *
 * Copyright (c) 2026 stringdotjar
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
// AUTO-GENERATED by the framework via a Python script, located inside of the scripts/
// folder in the repository root. Do NOT edit this file directly. If you wish to change
// a framework collection API, modify the script so it affects all files in the collection package.
// For more information, visit the framework's repository on GitHub: https://github.com/flixelgdx/flixelgdx
package org.flixelgdx.collections;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class FlixelByteArrayTest {

  @Test
  void addGetSet() {
    FlixelByteArray array = new FlixelByteArray();
    array.add((byte) 10);
    array.add((byte) 20);
    assertEquals(2, array.getSize());
    assertTrue(array.get(0) == (byte) 10);
    array.set(0, (byte) 99);
    assertTrue(array.get(0) == (byte) 99);
  }

  @Test
  void orderedRemoveShifts() {
    FlixelByteArray array = new FlixelByteArray();
    array.add((byte) 10);
    array.add((byte) 20);
    array.add((byte) 99);
    assertTrue(array.removeIndex(1) == (byte) 20);
    assertEquals(2, array.getSize());
    assertTrue(array.get(1) == (byte) 99);
  }

  @Test
  void unorderedRemoveSwapsLast() {
    FlixelByteArray array = new FlixelByteArray(false, 8);
    array.add((byte) 10);
    array.add((byte) 20);
    array.add((byte) 99);
    assertTrue(array.removeIndex(0) == (byte) 10);
    assertTrue(array.get(0) == (byte) 99);
    assertEquals(2, array.getSize());
  }

  @Test
  void indexOfAndContains() {
    FlixelByteArray array = new FlixelByteArray();
    array.add((byte) 10);
    array.add((byte) 20);
    assertEquals(1, array.indexOf((byte) 20));
    assertTrue(array.contains((byte) 10));
    assertTrue(array.removeValue((byte) 20));
    assertFalse(array.contains((byte) 20));
  }

  @Test
  void stackAndEnds() {
    FlixelByteArray array = new FlixelByteArray();
    array.add((byte) 10);
    array.add((byte) 20);
    array.add((byte) 99);
    assertTrue(array.first() == (byte) 10);
    assertTrue(array.peek() == (byte) 99);
    assertTrue(array.pop() == (byte) 99);
    assertEquals(2, array.getSize());
  }

  @Test
  void growSetSizeAndToArray() {
    FlixelByteArray array = new FlixelByteArray(2);
    for (int i = 0; i < 50; i++) {
      array.add((byte) 10);
    }
    assertEquals(50, array.getSize());
    byte[] copy = array.toArray();
    assertEquals(50, copy.length);
    array.setSize(0);
    assertTrue(array.isEmpty());
  }

  @Test
  void emptyAccessThrows() {
    FlixelByteArray array = new FlixelByteArray();
    assertTrue(array.isEmpty());
    assertThrows(IndexOutOfBoundsException.class, array::pop);
    assertThrows(IndexOutOfBoundsException.class, () -> array.get(0));
  }
}
