/*
 * MIT License
 *
 * Copyright (c) 2026 stringdotjar
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
// AUTO-GENERATED by the framework via a Python script, located inside of the scripts/
// folder in the repository root. Do NOT edit this file directly. If you wish to change
// a framework collection API, modify the script so it affects all files in the collection package.
// For more information, visit the framework's repository on GitHub: https://github.com/flixelgdx/flixelgdx
package org.flixelgdx.collections;

import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.Map;
import java.util.Random;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class FlixelObjectIntMapTest {

  @Test
  void basicsAndDefaults() {
    FlixelObjectIntMap<String> map = new FlixelObjectIntMap<>();
    assertEquals(0, map.get("x", 0));
    map.put("x", (int) 10);
    assertEquals((int) 10, map.get("x", 0));
    assertEquals((int) 11, map.increment("x", (int) 1));
    assertTrue(map.containsKey("x"));
    assertThrows(IllegalArgumentException.class, () -> map.put(null, (int) 1));
    assertEquals((int) 11, map.remove("x", (int) -1));
    assertFalse(map.containsKey("x"));
  }

  @Test
  void entriesIterateEveryEntry() {
    FlixelObjectIntMap<String> map = new FlixelObjectIntMap<>();
    map.put("a", (int) 1);
    map.put("b", (int) 2);
    map.put("c", (int) 3);

    int count = 0;
    int sum = 0;
    for (FlixelObjectIntMap.Entry<String> e : map.entries()) {
      sum += e.value;
      count++;
    }
    assertEquals(3, count);
    assertEquals((int) 6, sum);
  }

  @Test
  void behavesLikeHashMapUnderRandomOps() {
    FlixelObjectIntMap<Integer> ours = new FlixelObjectIntMap<>(4);
    Map<Integer, Integer> ref = new HashMap<>();
    Random random = new Random(33);
    for (int i = 0; i < 20000; i++) {
      Integer key = random.nextInt(400);
      int op = random.nextInt(3);
      if (op == 0) {
        int value = (int) random.nextInt(1000);
        ref.put(key, value);
        ours.put(key, value);
      } else if (op == 1) {
        Integer removed = ref.remove(key);
        assertEquals(removed == null ? (int) -999 : removed, ours.remove(key, (int) -999));
      } else {
        Integer v = ref.get(key);
        assertEquals(v == null ? (int) -999 : v, ours.get(key, (int) -999));
      }
      assertEquals(ref.size(), ours.getSize());
    }
  }
}
