/*
 * MIT License
 *
 * Copyright (c) 2026 stringdotjar
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
// AUTO-GENERATED by the framework via a Python script, located inside of the scripts/
// folder in the repository root. Do NOT edit this file directly. If you wish to change
// a framework collection API, modify the script so it affects all files in the collection package.
// For more information, visit the framework's repository on GitHub: https://github.com/flixelgdx/flixelgdx
package org.flixelgdx.collections;

import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.Map;
import java.util.Random;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class FlixelObjectFloatMapTest {

  @Test
  void basicsAndDefaults() {
    FlixelObjectFloatMap<String> map = new FlixelObjectFloatMap<>();
    assertEquals(0.0f, map.get("x", 0.0f), 1e-6f);
    map.put("x", (float) 10);
    assertEquals((float) 10, map.get("x", 0.0f), 1e-6f);
    assertEquals((float) 11, map.increment("x", (float) 1), 1e-6f);
    assertTrue(map.containsKey("x"));
    assertThrows(IllegalArgumentException.class, () -> map.put(null, (float) 1));
    assertEquals((float) 11, map.remove("x", (float) -1), 1e-6f);
    assertFalse(map.containsKey("x"));
  }

  @Test
  void entriesIterateEveryEntry() {
    FlixelObjectFloatMap<String> map = new FlixelObjectFloatMap<>();
    map.put("a", (float) 1);
    map.put("b", (float) 2);
    map.put("c", (float) 3);

    int count = 0;
    float sum = 0.0f;
    for (FlixelObjectFloatMap.Entry<String> e : map.entries()) {
      sum += e.value;
      count++;
    }
    assertEquals(3, count);
    assertEquals((float) 6, sum, 1e-6f);
  }

  @Test
  void behavesLikeHashMapUnderRandomOps() {
    FlixelObjectFloatMap<Integer> ours = new FlixelObjectFloatMap<>(4);
    Map<Integer, Float> ref = new HashMap<>();
    Random random = new Random(33);
    for (int i = 0; i < 20000; i++) {
      Integer key = random.nextInt(400);
      int op = random.nextInt(3);
      if (op == 0) {
        float value = (float) random.nextInt(1000);
        ref.put(key, value);
        ours.put(key, value);
      } else if (op == 1) {
        Float removed = ref.remove(key);
        assertEquals(removed == null ? (float) -999 : removed, ours.remove(key, (float) -999), 1e-6f);
      } else {
        Float v = ref.get(key);
        assertEquals(v == null ? (float) -999 : v, ours.get(key, (float) -999), 1e-6f);
      }
      assertEquals(ref.size(), ours.getSize());
    }
  }
}
