import java.util.*

plugins {
  id("flixelgdx.android-library")
}

// The Android backend is a fail-fast placeholder until it is brought onto the framework's bgfx +
// SDL3 stack (through the NDK) in a later phase. It depends only on the core API, so there is no
// libGDX, no gdx native platform jars, and no basisu on the classpath. The consumer keep-rules are
// scoped to the framework's own packages, which is all a reflection-free core needs.

val reflectionProfileRaw = (findProperty("flixelReflectionProfile") ?: "STANDARD")
  .toString().trim().uppercase(Locale.ROOT)
val reflectionProfile =
  if (reflectionProfileRaw in listOf("SIMPLE", "STANDARD", "ALL")) reflectionProfileRaw else "STANDARD"
val reflectionExtraPackages = (findProperty("flixelReflectionExtraPackages") ?: "")
  .toString()
  .split(",")
  .map { it.trim() }
  .filter { it.isNotEmpty() }

val reflectionPackagePrefixes = mutableListOf("org.flixelgdx")
reflectionPackagePrefixes += reflectionExtraPackages

val generateReflectionConsumerRules = tasks.register("generateReflectionConsumerRules") {
  val outputDir = layout.buildDirectory.dir("generated/flixel-reflection")
  outputs.dir(outputDir)

  doLast {
    val out = outputDir.get().file("consumer-rules.pro").asFile
    out.parentFile.mkdirs()
    val keepRules = reflectionPackagePrefixes.joinToString("\n") { pkg ->
      "-keep class $pkg.** { *; }"
    }
    out.writeText(
      """# Auto-generated by flixelgdx-android for consumer keep-rules profile: $reflectionProfile
-keepattributes Signature,InnerClasses,EnclosingMethod,*Annotation*
$keepRules
"""
    )
  }
}

android {
  namespace = "org.flixelgdx"
  compileSdk = 36

  defaultConfig {
    multiDexEnabled = true
    minSdk = 24
    consumerProguardFiles("${layout.buildDirectory.get()}/generated/flixel-reflection/consumer-rules.pro")
  }
  compileOptions {
    isCoreLibraryDesugaringEnabled = true
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
  }
}

tasks.matching { it.name == "preBuild" }.configureEach {
  dependsOn(generateReflectionConsumerRules)
}

dependencies {
  "coreLibraryDesugaring"(libs.desugar.jdk.libs)

  api(project(":flixelgdx-core"))
  api(libs.multidex)
  implementation(libs.jetbrains.annotations)
}
