import java.util.Locale

plugins {
  id("flixelgdx.android-library")
}

val reflectionProfileRaw = (findProperty("flixelReflectionProfile") ?: "STANDARD")
  .toString().trim().uppercase(Locale.ROOT)
val reflectionProfile =
  if (reflectionProfileRaw in listOf("SIMPLE", "STANDARD", "ALL")) reflectionProfileRaw else "STANDARD"
val reflectionExtraPackages = (findProperty("flixelReflectionExtraPackages") ?: "")
  .toString()
  .split(",")
  .map { it.trim() }
  .filter { it.isNotEmpty() }

val reflectionPackagePrefixes = mutableListOf("org.flixelgdx")
reflectionPackagePrefixes += reflectionExtraPackages

val generateReflectionConsumerRules = tasks.register("generateReflectionConsumerRules") {
  val outputDir = layout.buildDirectory.dir("generated/flixel-reflection")
  outputs.dir(outputDir)

  doLast {
    val out = outputDir.get().file("consumer-rules.pro").asFile
    out.parentFile.mkdirs()
    val keepRules = reflectionPackagePrefixes.joinToString("\n") { pkg ->
      "-keep class $pkg.** { *; }"
    }
    out.writeText(
      """# Auto-generated by flixelgdx-android for consumer keep-rules profile: $reflectionProfile
-keepattributes Signature,InnerClasses,EnclosingMethod,*Annotation*
$keepRules
"""
    )
  }
}

android {
  namespace = "org.flixelgdx"
  compileSdk = 36

  // NDK r28b; AGP downloads this automatically on first build if not already installed.
  ndkVersion = "28.2.13676358"

  defaultConfig {
    multiDexEnabled = true
    minSdk = 24
    consumerProguardFiles("${layout.buildDirectory.get()}/generated/flixel-reflection/consumer-rules.pro")

    ndk {
      abiFilters += listOf("arm64-v8a", "armeabi-v7a", "x86_64")
    }

    externalNativeBuild {
      cmake {
        // Use -Os for code-size optimization to keep the AAR compact.
        arguments += "-DANDROID_STL=c++_static"
      }
    }
  }
  compileOptions {
    isCoreLibraryDesugaringEnabled = true
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
  }
  externalNativeBuild {
    cmake {
      path = file("src/main/cpp/CMakeLists.txt")
      // SDK CMake 3.22.1 is downloaded automatically by AGP when not already present.
      version = "3.22.1"
    }
  }
}

tasks.matching { it.name == "preBuild" }.configureEach {
  dependsOn(generateReflectionConsumerRules)
}

dependencies {
  "coreLibraryDesugaring"(libs.desugar.jdk.libs)

  api(project(":flixelgdx-core"))
  api(project(":flixelgdx-miniaudio"))
  api(libs.multidex)
  implementation(libs.jetbrains.annotations)
}
