/*
 * MIT License
 *
 * Copyright (c) 2026 stringdotjar
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.flixelgdx.json;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Exercises the code generated by the {@code @JsonSerializable} annotation processor: the
 * {@code <Class>JsonSerializer} classes are produced at compile time and used here with no
 * reflection.
 */
class FlixelJsonSerializableTest {

  @Test
  void scalarFieldsRoundTrip() {
    SaveData save = new SaveData();
    save.highScore = 1200;
    save.playerName = "Ada";
    save.volume = 0.75f;
    save.tutorialDone = true;

    String json = SaveDataJsonSerializer.toJson(save);
    SaveData back = SaveDataJsonSerializer.fromJson(FlixelJson.parse(json));

    assertEquals(1200, back.highScore);
    assertEquals("Ada", back.playerName);
    assertEquals(0.75f, back.volume, 1e-6f);
    assertTrue(back.tutorialDone);
  }

  @Test
  void nestedTypeRoundTrips() {
    Profile profile = new Profile();
    profile.name = "Grace";
    profile.best = new SaveData();
    profile.best.highScore = 999;
    profile.best.playerName = "Grace";

    String json = ProfileJsonSerializer.toJson(profile);
    Profile back = ProfileJsonSerializer.fromJson(FlixelJson.parse(json));

    assertEquals("Grace", back.name);
    assertNotNull(back.best);
    assertEquals(999, back.best.highScore);
    assertEquals("Grace", back.best.playerName);
  }

  @Test
  void stringEscapingSurvivesRoundTrip() {
    SaveData save = new SaveData();
    save.playerName = "line1\n\"quoted\"\tend";

    SaveData back = SaveDataJsonSerializer.fromJson(FlixelJson.parse(SaveDataJsonSerializer.toJson(save)));
    assertEquals("line1\n\"quoted\"\tend", back.playerName);
  }
}
