/*
 * MIT License
 *
 * Copyright (c) 2026 stringdotjar
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.flixelgdx.json;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Exercises the code generated by the {@code @JsonSerializable} annotation processor: the
 * {@code <Class>JsonSerializer} classes are produced at compile time and used here with no
 * reflection.
 */
class FlixelJsonSerializableTest {

  @Test
  void scalarFieldsRoundTrip() {
    SaveData save = new SaveData();
    save.highScore = 1200;
    save.playerName = "Ada";
    save.volume = 0.75f;
    save.tutorialDone = true;

    String json = SaveDataJsonSerializer.toJson(save);
    SaveData back = SaveDataJsonSerializer.fromJson(FlixelJson.parse(json));

    assertEquals(1200, back.highScore);
    assertEquals("Ada", back.playerName);
    assertEquals(0.75f, back.volume, 1e-6f);
    assertTrue(back.tutorialDone);
  }

  @Test
  void nestedTypeRoundTrips() {
    Profile profile = new Profile();
    profile.name = "Grace";
    profile.best = new SaveData();
    profile.best.highScore = 999;
    profile.best.playerName = "Grace";

    String json = ProfileJsonSerializer.toJson(profile);
    Profile back = ProfileJsonSerializer.fromJson(FlixelJson.parse(json));

    assertEquals("Grace", back.name);
    assertNotNull(back.best);
    assertEquals(999, back.best.highScore);
    assertEquals("Grace", back.best.playerName);
  }

  @Test
  void arraysAndEnumsRoundTrip() {
    Loadout loadout = new Loadout();
    loadout.scores = new int[] { 10, 20, 30 };
    loadout.tags = new String[] { "fire", "ice" };
    loadout.rarity = Loadout.Rarity.LEGENDARY;
    loadout.unlocked = new Loadout.Rarity[] { Loadout.Rarity.COMMON, Loadout.Rarity.RARE };

    SaveData first = new SaveData();
    first.highScore = 5;
    first.playerName = "A";
    SaveData second = new SaveData();
    second.highScore = 9;
    second.playerName = "B";
    loadout.saves = new SaveData[] { first, second };

    String json = LoadoutJsonSerializer.toJson(loadout);
    Loadout back = LoadoutJsonSerializer.fromJson(FlixelJson.parse(json));

    assertArrayEquals(new int[] { 10, 20, 30 }, back.scores);
    assertArrayEquals(new String[] { "fire", "ice" }, back.tags);
    assertEquals(Loadout.Rarity.LEGENDARY, back.rarity);
    assertArrayEquals(new Loadout.Rarity[] { Loadout.Rarity.COMMON, Loadout.Rarity.RARE }, back.unlocked);
    assertEquals(2, back.saves.length);
    assertEquals(5, back.saves[0].highScore);
    assertEquals("A", back.saves[0].playerName);
    assertEquals(9, back.saves[1].highScore);
    assertEquals("B", back.saves[1].playerName);
  }

  @Test
  void stringEscapingSurvivesRoundTrip() {
    SaveData save = new SaveData();
    save.playerName = "line1\n\"quoted\"\tend";

    SaveData back = SaveDataJsonSerializer.fromJson(FlixelJson.parse(SaveDataJsonSerializer.toJson(save)));
    assertEquals("line1\n\"quoted\"\tend", back.playerName);
  }
}
