/**
 * FlixelGDX's own minimal XML parser, sized for game data files such as Sparrow atlases and tile
 * maps.
 *
 * <p>{@link org.flixelgdx.xml.FlixelXml FlixelXml} parses text into a tree of
 * {@link org.flixelgdx.xml.FlixelXmlElement FlixelXmlElement} nodes that support attribute
 * reads, name-filtered child iteration, and text content. It has no platform dependencies and
 * behaves identically on desktop, Android, web, and native images. It is not a validating parser
 * and does not handle namespaces, which game data formats do not need.
 *
 * <h2>Example - reading a Sparrow atlas</h2>
 * <pre>{@code
 * String xml = Flixel.files.internal("images/hero.xml").readString();
 * FlixelXmlElement root = FlixelXml.parse(xml);
 *
 * for (FlixelXmlElement frame : root.getChildrenByName("SubTexture")) {
 *   String name = frame.getAttribute("name");
 *   int x = Integer.parseInt(frame.getAttribute("x"));
 *   int y = Integer.parseInt(frame.getAttribute("y"));
 *   int w = Integer.parseInt(frame.getAttribute("width"));
 *   int h = Integer.parseInt(frame.getAttribute("height"));
 *   // register the frame region...
 * }
 * }</pre>
 *
 * <p>The parser skips XML declarations, comments, DOCTYPEs, and CDATA framing, all of which
 * are common in atlas files generated by tools like TexturePacker.
 *
 * @see org.flixelgdx.xml.FlixelXml
 * @see org.flixelgdx.xml.FlixelXmlElement
 */
package org.flixelgdx.xml;
